version: '3.4'

services:
    servidor:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        network_mode: host
        expose:
            - "8080"
        ports:
            - "0.0.0.0:8080:8080"
        volumes:
            - ./server:/pongame/server
            - ./thrift:/pongame/thrift
        stdin_open: true
        tty: true
        
    cliente:
        build:
            context: .
            dockerfile: ./client/Dockerfile
        network_mode: host
        expose:
            - "8080"
        ports:
            - "0.0.0.0:8080:8080"
        volumes:
            - ./client:/pongame/client
            - ./thrift:/pongame/thrift
        stdin_open: true
        tty: true