/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-06-12")
public class Ball implements org.apache.thrift.TBase<Ball, Ball._Fields>, java.io.Serializable, Cloneable, Comparable<Ball> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Ball");

  private static final org.apache.thrift.protocol.TField POSITION_FIELD_DESC = new org.apache.thrift.protocol.TField("position", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField SPEED_ON_Y_FIELD_DESC = new org.apache.thrift.protocol.TField("speedOnY", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField SPEED_ON_X_FIELD_DESC = new org.apache.thrift.protocol.TField("speedOnX", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new BallStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new BallTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable Position position; // required
  public int speedOnY; // required
  public int speedOnX; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    POSITION((short)1, "position"),
    SPEED_ON_Y((short)2, "speedOnY"),
    SPEED_ON_X((short)3, "speedOnX");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // POSITION
          return POSITION;
        case 2: // SPEED_ON_Y
          return SPEED_ON_Y;
        case 3: // SPEED_ON_X
          return SPEED_ON_X;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SPEEDONY_ISSET_ID = 0;
  private static final int __SPEEDONX_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.POSITION, new org.apache.thrift.meta_data.FieldMetaData("position", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "Position")));
    tmpMap.put(_Fields.SPEED_ON_Y, new org.apache.thrift.meta_data.FieldMetaData("speedOnY", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SPEED_ON_X, new org.apache.thrift.meta_data.FieldMetaData("speedOnX", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Ball.class, metaDataMap);
  }

  public Ball() {
  }

  public Ball(
    Position position,
    int speedOnY,
    int speedOnX)
  {
    this();
    this.position = position;
    this.speedOnY = speedOnY;
    setSpeedOnYIsSet(true);
    this.speedOnX = speedOnX;
    setSpeedOnXIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Ball(Ball other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetPosition()) {
      this.position = new Position(other.position);
    }
    this.speedOnY = other.speedOnY;
    this.speedOnX = other.speedOnX;
  }

  public Ball deepCopy() {
    return new Ball(this);
  }

  @Override
  public void clear() {
    this.position = null;
    setSpeedOnYIsSet(false);
    this.speedOnY = 0;
    setSpeedOnXIsSet(false);
    this.speedOnX = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public Position getPosition() {
    return this.position;
  }

  public Ball setPosition(@org.apache.thrift.annotation.Nullable Position position) {
    this.position = position;
    return this;
  }

  public void unsetPosition() {
    this.position = null;
  }

  /** Returns true if field position is set (has been assigned a value) and false otherwise */
  public boolean isSetPosition() {
    return this.position != null;
  }

  public void setPositionIsSet(boolean value) {
    if (!value) {
      this.position = null;
    }
  }

  public int getSpeedOnY() {
    return this.speedOnY;
  }

  public Ball setSpeedOnY(int speedOnY) {
    this.speedOnY = speedOnY;
    setSpeedOnYIsSet(true);
    return this;
  }

  public void unsetSpeedOnY() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SPEEDONY_ISSET_ID);
  }

  /** Returns true if field speedOnY is set (has been assigned a value) and false otherwise */
  public boolean isSetSpeedOnY() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SPEEDONY_ISSET_ID);
  }

  public void setSpeedOnYIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SPEEDONY_ISSET_ID, value);
  }

  public int getSpeedOnX() {
    return this.speedOnX;
  }

  public Ball setSpeedOnX(int speedOnX) {
    this.speedOnX = speedOnX;
    setSpeedOnXIsSet(true);
    return this;
  }

  public void unsetSpeedOnX() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SPEEDONX_ISSET_ID);
  }

  /** Returns true if field speedOnX is set (has been assigned a value) and false otherwise */
  public boolean isSetSpeedOnX() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SPEEDONX_ISSET_ID);
  }

  public void setSpeedOnXIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SPEEDONX_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case POSITION:
      if (value == null) {
        unsetPosition();
      } else {
        setPosition((Position)value);
      }
      break;

    case SPEED_ON_Y:
      if (value == null) {
        unsetSpeedOnY();
      } else {
        setSpeedOnY((java.lang.Integer)value);
      }
      break;

    case SPEED_ON_X:
      if (value == null) {
        unsetSpeedOnX();
      } else {
        setSpeedOnX((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case POSITION:
      return getPosition();

    case SPEED_ON_Y:
      return getSpeedOnY();

    case SPEED_ON_X:
      return getSpeedOnX();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case POSITION:
      return isSetPosition();
    case SPEED_ON_Y:
      return isSetSpeedOnY();
    case SPEED_ON_X:
      return isSetSpeedOnX();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Ball)
      return this.equals((Ball)that);
    return false;
  }

  public boolean equals(Ball that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_position = true && this.isSetPosition();
    boolean that_present_position = true && that.isSetPosition();
    if (this_present_position || that_present_position) {
      if (!(this_present_position && that_present_position))
        return false;
      if (!this.position.equals(that.position))
        return false;
    }

    boolean this_present_speedOnY = true;
    boolean that_present_speedOnY = true;
    if (this_present_speedOnY || that_present_speedOnY) {
      if (!(this_present_speedOnY && that_present_speedOnY))
        return false;
      if (this.speedOnY != that.speedOnY)
        return false;
    }

    boolean this_present_speedOnX = true;
    boolean that_present_speedOnX = true;
    if (this_present_speedOnX || that_present_speedOnX) {
      if (!(this_present_speedOnX && that_present_speedOnX))
        return false;
      if (this.speedOnX != that.speedOnX)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPosition()) ? 131071 : 524287);
    if (isSetPosition())
      hashCode = hashCode * 8191 + position.hashCode();

    hashCode = hashCode * 8191 + speedOnY;

    hashCode = hashCode * 8191 + speedOnX;

    return hashCode;
  }

  @Override
  public int compareTo(Ball other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetPosition()).compareTo(other.isSetPosition());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPosition()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.position, other.position);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSpeedOnY()).compareTo(other.isSetSpeedOnY());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSpeedOnY()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.speedOnY, other.speedOnY);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSpeedOnX()).compareTo(other.isSetSpeedOnX());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSpeedOnX()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.speedOnX, other.speedOnX);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Ball(");
    boolean first = true;

    sb.append("position:");
    if (this.position == null) {
      sb.append("null");
    } else {
      sb.append(this.position);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("speedOnY:");
    sb.append(this.speedOnY);
    first = false;
    if (!first) sb.append(", ");
    sb.append("speedOnX:");
    sb.append(this.speedOnX);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BallStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BallStandardScheme getScheme() {
      return new BallStandardScheme();
    }
  }

  private static class BallStandardScheme extends org.apache.thrift.scheme.StandardScheme<Ball> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Ball struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // POSITION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.position = new Position();
              struct.position.read(iprot);
              struct.setPositionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SPEED_ON_Y
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.speedOnY = iprot.readI32();
              struct.setSpeedOnYIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SPEED_ON_X
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.speedOnX = iprot.readI32();
              struct.setSpeedOnXIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Ball struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.position != null) {
        oprot.writeFieldBegin(POSITION_FIELD_DESC);
        struct.position.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SPEED_ON_Y_FIELD_DESC);
      oprot.writeI32(struct.speedOnY);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SPEED_ON_X_FIELD_DESC);
      oprot.writeI32(struct.speedOnX);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BallTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BallTupleScheme getScheme() {
      return new BallTupleScheme();
    }
  }

  private static class BallTupleScheme extends org.apache.thrift.scheme.TupleScheme<Ball> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Ball struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPosition()) {
        optionals.set(0);
      }
      if (struct.isSetSpeedOnY()) {
        optionals.set(1);
      }
      if (struct.isSetSpeedOnX()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetPosition()) {
        struct.position.write(oprot);
      }
      if (struct.isSetSpeedOnY()) {
        oprot.writeI32(struct.speedOnY);
      }
      if (struct.isSetSpeedOnX()) {
        oprot.writeI32(struct.speedOnX);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Ball struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.position = new Position();
        struct.position.read(iprot);
        struct.setPositionIsSet(true);
      }
      if (incoming.get(1)) {
        struct.speedOnY = iprot.readI32();
        struct.setSpeedOnYIsSet(true);
      }
      if (incoming.get(2)) {
        struct.speedOnX = iprot.readI32();
        struct.setSpeedOnXIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

